/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EntropyEncryptionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confidentialProtocolId"
      | "encryptAndStore"
      | "encryptAndStoreWithEntropy"
      | "entropyOracle"
      | "entropyRequests"
      | "getEncryptedValue"
      | "getEntropyOracle"
      | "isInitialized"
      | "requestEntropy"
      | "updateValue"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EntropyRequested"
      | "ValueEncrypted"
      | "ValueEncryptedWithEntropy"
      | "ValueUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "encryptAndStore",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "encryptAndStoreWithEntropy",
    values: [BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "entropyOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "entropyRequests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedValue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEntropyOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isInitialized",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestEntropy",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateValue",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "encryptAndStore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "encryptAndStoreWithEntropy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "entropyOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "entropyRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEntropyOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isInitialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestEntropy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateValue",
    data: BytesLike
  ): Result;
}

export namespace EntropyRequestedEvent {
  export type InputTuple = [requestId: BigNumberish, caller: AddressLike];
  export type OutputTuple = [requestId: bigint, caller: string];
  export interface OutputObject {
    requestId: bigint;
    caller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValueEncryptedEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValueEncryptedWithEntropyEvent {
  export type InputTuple = [requestId: BigNumberish, user: AddressLike];
  export type OutputTuple = [requestId: bigint, user: string];
  export interface OutputObject {
    requestId: bigint;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValueUpdatedEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EntropyEncryption extends BaseContract {
  connect(runner?: ContractRunner | null): EntropyEncryption;
  waitForDeployment(): Promise<this>;

  interface: EntropyEncryptionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  encryptAndStore: TypedContractMethod<
    [encryptedInput: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  encryptAndStoreWithEntropy: TypedContractMethod<
    [encryptedInput: BytesLike, inputProof: BytesLike, requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  entropyOracle: TypedContractMethod<[], [string], "view">;

  entropyRequests: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  getEncryptedValue: TypedContractMethod<[], [string], "view">;

  getEntropyOracle: TypedContractMethod<[], [string], "view">;

  isInitialized: TypedContractMethod<[], [boolean], "view">;

  requestEntropy: TypedContractMethod<[tag: BytesLike], [bigint], "payable">;

  updateValue: TypedContractMethod<
    [encryptedInput: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "encryptAndStore"
  ): TypedContractMethod<
    [encryptedInput: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "encryptAndStoreWithEntropy"
  ): TypedContractMethod<
    [encryptedInput: BytesLike, inputProof: BytesLike, requestId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "entropyOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "entropyRequests"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "getEncryptedValue"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getEntropyOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isInitialized"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "requestEntropy"
  ): TypedContractMethod<[tag: BytesLike], [bigint], "payable">;
  getFunction(
    nameOrSignature: "updateValue"
  ): TypedContractMethod<
    [encryptedInput: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "EntropyRequested"
  ): TypedContractEvent<
    EntropyRequestedEvent.InputTuple,
    EntropyRequestedEvent.OutputTuple,
    EntropyRequestedEvent.OutputObject
  >;
  getEvent(
    key: "ValueEncrypted"
  ): TypedContractEvent<
    ValueEncryptedEvent.InputTuple,
    ValueEncryptedEvent.OutputTuple,
    ValueEncryptedEvent.OutputObject
  >;
  getEvent(
    key: "ValueEncryptedWithEntropy"
  ): TypedContractEvent<
    ValueEncryptedWithEntropyEvent.InputTuple,
    ValueEncryptedWithEntropyEvent.OutputTuple,
    ValueEncryptedWithEntropyEvent.OutputObject
  >;
  getEvent(
    key: "ValueUpdated"
  ): TypedContractEvent<
    ValueUpdatedEvent.InputTuple,
    ValueUpdatedEvent.OutputTuple,
    ValueUpdatedEvent.OutputObject
  >;

  filters: {
    "EntropyRequested(uint256,address)": TypedContractEvent<
      EntropyRequestedEvent.InputTuple,
      EntropyRequestedEvent.OutputTuple,
      EntropyRequestedEvent.OutputObject
    >;
    EntropyRequested: TypedContractEvent<
      EntropyRequestedEvent.InputTuple,
      EntropyRequestedEvent.OutputTuple,
      EntropyRequestedEvent.OutputObject
    >;

    "ValueEncrypted(address)": TypedContractEvent<
      ValueEncryptedEvent.InputTuple,
      ValueEncryptedEvent.OutputTuple,
      ValueEncryptedEvent.OutputObject
    >;
    ValueEncrypted: TypedContractEvent<
      ValueEncryptedEvent.InputTuple,
      ValueEncryptedEvent.OutputTuple,
      ValueEncryptedEvent.OutputObject
    >;

    "ValueEncryptedWithEntropy(uint256,address)": TypedContractEvent<
      ValueEncryptedWithEntropyEvent.InputTuple,
      ValueEncryptedWithEntropyEvent.OutputTuple,
      ValueEncryptedWithEntropyEvent.OutputObject
    >;
    ValueEncryptedWithEntropy: TypedContractEvent<
      ValueEncryptedWithEntropyEvent.InputTuple,
      ValueEncryptedWithEntropyEvent.OutputTuple,
      ValueEncryptedWithEntropyEvent.OutputObject
    >;

    "ValueUpdated(address)": TypedContractEvent<
      ValueUpdatedEvent.InputTuple,
      ValueUpdatedEvent.OutputTuple,
      ValueUpdatedEvent.OutputObject
    >;
    ValueUpdated: TypedContractEvent<
      ValueUpdatedEvent.InputTuple,
      ValueUpdatedEvent.OutputTuple,
      ValueUpdatedEvent.OutputObject
    >;
  };
}
